[r2]
type = s3
provider = Cloudflare
access_key_id = <set-locally>
secret_access_key = <set-locally>
endpoint = https://example-account.r2.cloudflarestorage.com

[hetzner]
type = s3
provider = Other
env_auth = false
access_key_id = <set-locally>
secret_access_key = <set-locally>
endpoint = https://fsn1.your-objectstorage.com
